apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-access-management
data:
  security.yaml: |
{{ .Files.Get "jcasc/security.yaml" | indent 4 }}

  authorization.yaml: |
{{ .Files.Get "jcasc/authorization.yaml" | indent 4 }}

  libraries.yaml: |
{{ .Files.Get "jcasc/libraries.yaml" | indent 4 }}

  credentials.yaml: |
{{ .Files.Get "jcasc/credentials.yaml" | indent 4 }}