jcasc:
  security: |
    jenkins:
      securityRealm:
        github:
          clientID: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          githubWebUri: https://github.com
          githubApiUri: https://api.github.com
          oauthScopes: "read:org,user:email"

  authorization: |
    jenkins:
      authorizationStrategy:
        roleBased:
          roles:
            global:
              #
              # ===========================
              # ADMIN
              # ===========================
              #
              - name: Admin
                description: Full Jenkins Administration
                permissions:
                  - "Overall/Administer"
                entries:
                  - user: "priyanshu3103"

              #
              # ===========================
              # DEVOPS
              # ===========================
              #
              - name: DevOps
                description: Manage Jenkins infrastructure and pipelines
                permissions:
                  - "Overall/Read"

                  - "Job/Create"
                  - "Job/Delete"
                  - "Job/Configure"
                  - "Job/Read"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Discover"
                  - "Job/Move"
                  - "Job/Workspace"

                  - "Run/Delete"
                  - "Run/Replay"
                  - "Run/Update"

                  - "View/Read"

                  - "Credentials/View"

                  - "agents/Build"
                  - "agents/Configure"
                  - "agents/Connect"
                  - "agents/Create"
                  - "agents/Delete"
                  - "agents/Disconnect"

                entries:
                  - user: "priyanshu3103"

              #
              # ===========================
              # DEVELOPERS
              # ===========================
              #
              - name: Developer
                description: Build applications
                permissions:
                  - "Overall/Read"

                  - "Job/Read"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Discover"
                  - "Job/Workspace"

                  - "Run/Replay"

                  - "View/Read"

                entries:
                  - user: "priyanshu3103"

              #
              # ===========================
              # QA
              # ===========================
              #
              - name: QA
                description: Execute test pipelines
                permissions:
                  - "Overall/Read"

                  - "Job/Read"
                  - "Job/Build"
                  - "Job/Discover"

                  - "View/Read"

                entries:
                  - user: "priyanshu3103"

            items: []

            agentss: []

  libraries: |
    unclassified:
      globalLibraries:
        libraries: []