jcasc:
  security: |
    jenkins:
      securityRealm:
        github:
          clientID: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          githubWebUri: https://github.com
          githubApiUri: https://api.github.com
          oauthScopes: "read:org,user:email"

  authorization: |
    jenkins:
      authorizationStrategy:
        github:
          adminUserNames: "priyanshu3103"
          organizationNames: "priyanshu-devops-release"
          useRepositoryPermissions: false
          authenticatedUserReadPermission: true
          authenticatedUserCreateJobPermission: true
          allowGithubWebHookPermission: false
          allowAnonymousReadPermission: false
          allowAnonymousJobStatusPermission: false

  credentials: |
    credentials:
      system:
        domainCredentials: []

  libraries: |
    unclassified:
      globalLibraries:
        libraries: []