jcasc:
  security: |
    jenkins:
      securityRealm:
        github:
          clientID: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          githubWebUri: https://github.com
          githubApiUri: https://api.github.com
          oauthScopes: "read:org,user:email"

  authorization: |
    jenkins:
      authorizationStrategy:
        roleBased:
          roles:
            global:
              #
              # ===========================
              # ADMIN
              # ===========================
              - name: Admin
                description: Full Jenkins Administration
                permissions:
                  - "Overall/Administer"
                entries:
                  - user: "priyanshu3103"
              # ===========================
              # AUTHENTICATED
              # ===========================    
              - name: Authenticated
                permissions:
                  - "Overall/Read"
                entries:
                  - user: "priyanshu3103"
                  - user: "mayurs2006"
            # ===========================
            # PROJECT ROLES
            # ===========================
            items:
              - name: SeedJob
                pattern: "^Seed Job$"
                permissions:
                  - "Job/Read"
                  - "Job/Build"
                  - "Job/Configure"
                entries:
                  - user: "priyanshu3103"

              - name: Applications
                pattern: "^Applications(/.*)?$"
                permissions:
                  - "Job/Read"
                  - "Job/Discover"
                  - "Job/Build"
                  - "Job/Workspace"
                entries:
                  - user: "priyanshu3103"
                  - user: "mayurs2006"

              - name: Infrastructure
                pattern: "^Infrastructure(/.*)?$"
                permissions:
                  - "Job/Read"
                  - "Job/Discover"
                  - "Job/Build"
                  - "Job/Workspace"
                entries:
                  - user: "priyanshu3103"
            agents: []

  libraries: |
    unclassified:
      globalLibraries:
        libraries: []

  jobs: |
   jobs:
    - script: >
        freeStyleJob('Seed Job') {
          description('Creates and updates all Jenkins jobs')

          label('jenkins-agent')

          scm {
            git {
              remote {
                url('https://github.com/priyanshu-devops-release/jenkins-config-management.git')
                credentials('github-token')
              }
              branch('master')
            }
          }

          steps {
            jobDsl {
              targets('''
                  jobdsl/folders.groovy
                  jobdsl/tools.groovy
                  jobdsl/pipelines/*.groovy
              ''')
              removedJobAction('DELETE')
              removedViewAction('DELETE')
              removedConfigFilesAction('DELETE')
              lookupStrategy('JENKINS_ROOT')
            }
          }

          logRotator {
            numToKeep(20)
          }
        }